apiVersion: v1
kind: ConfigMap
metadata:
  name: next-gen-ui
  namespace: {{ .Release.Namespace }}
data:
  API_URL: '{{ .Values.global.loadbalancerURL }}/gateway'
  DEPLOYMENT_TYPE: ON_PREM
  HARNESS_ENABLE_NG_AUTH_UI_PLACEHOLDER: "true"
  HARNESS_BROWSER_ROUTER_ENABLED: "true"
  HARNESS_CLUSTER_URL: ''
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
