apiVersion: v1
kind: ConfigMap
metadata:
  name: ti-service
  namespace: {{ .Release.Namespace }}
data:
  TI_SERVICE_TIMESCALE_HOST: timescaledb-single-chart.{{ .Release.Namespace }}
  TI_SERVICE_TIMESCALE_PORT: "5432"
  TI_SERVICE_DB_NAME: harnessti
  TI_SERVICE_MONGODB_DB_NAME: ti-harness
  TI_SERVICE_HYPER_TABLE: evaluation
  TI_SERVICE_DISABLE_AUTH: "true"
  TI_SERVICE_SELECTION_HYPER_TABLE: selection
  TI_SERVICE_COVERAGE_HYPER_TABLE: coverage
  {{- if .Values.useSSL }}
  TI_SERVICE_TIMESCALE_SSL_MODE: "require"
  {{- end }}

  # Protocol needs to be set to empty because ti-service uses go-redis library which doesn't accept protocol based strings
  {{- $dbContext := deepCopy .Values.global.database.redis }}
  {{- $_ := set $dbContext "protocol" "" }}
  EVENTS_FRAMEWORK_REDIS_URL: {{ include "harnesscommon.dbconnection.redisConnection" (dict "context" $dbContext) }}
  EVENTS_FRAMEWORK_REDIS_USE_SENTINEL: {{ .Values.global.database.redis.installed | quote }}
  EVENTS_FRAMEWORK_REDIS_SENTINEL_MASTER_NAME: 'harness-redis'
  EVENTS_FRAMEWORK_REDIS_SENTINEL_URLS: {{ include "harnesscommon.dbconnection.redisConnection" (dict "context" $dbContext) }}
  TI_SERVICE_GLOBAL_TOKEN: 78d16b66-4b4c-11eb-8377-acde48001122
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
