apiVersion: batch/v1
kind: Job
metadata:
  name: ti-migration-{{ lower ( randAlphaNum 6 ) }}
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    {{- include "ti-service.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ti-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: migrate
        image: {{ include "common.images.image" (dict "imageRoot" .Values.jobs.migrate.image "global" .Values.global) }}
        imagePullPolicy: {{ .Values.jobs.migrate.image.pullPolicy}}
        command: ["/bin/bash", "-c", "sleep 300 && /opt/harness/migrate.sh" ]
        resources:
          {{- toYaml .Values.jobresources | nindent 10 }}
        env:
          {{- include "harnesscommon.dbconnection.mongoEnv" . | indent 10 }}
          - name: TI_SERVICE_MONGODB_CONN_STR
            value: {{ include "harnesscommon.dbconnection.mongoConnection" (dict "database" "ti-harness" "context" $) }}
          {{- include "harnesscommon.dbconnection.timescaleEnv" (dict "passwordVariableName" "TI_SERVICE_TIMESCALE_PASSWORD" "userVariableName" "TI_SERVICE_TIMESCALE_USERNAME" "context" $) | indent 10}}
          {{- include "harnesscommon.dbconnection.timescaleSslEnv" (dict "sslModeVariableName" "TI_SERVICE_TIMESCALE_SSL_MODE" "sslModeValue" "verify-full" "enableSslVariableName" "TI_SERVICE_TIMESCALE_ENABLE_SSL" "certPathVariableName" "TI_SERVICE_TIMESCALE_SSL_CERT_PATH" "certPathValue" "/opt/harness/svc/timescale_ca.pem" "context" $ ) | nindent 10 }}    
          - name: TI_SERVICE_TIMESCALE_HOST
            value: {{ include "harnesscommon.dbconnection.timescaleHost" (dict "context" $) }}
          - name: TI_SERVICE_TIMESCALE_PORT
            value: {{ include "harnesscommon.dbconnection.timescalePort" (dict "context" $) | quote }}
      {{- if .Values.global.database.timescaledb.sslEnabled }}
        volumeMounts:
          - name: timescaledb-cert
            mountPath: /opt/harness/svc
      volumes:
      - name: timescaledb-cert
        secret:
          secretName: {{ .Values.global.database.timescaledb.certName }}
          items:
          - key: {{ .Values.global.database.timescaledb.certKey }}
            path: timescale_ca.pem
      {{- end }}  
      restartPolicy: Never
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
