apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
data:
  MANAGER_URL: {{ include "gateway.managerUrl" . | quote }}
  MANAGER_PUBLIC_URL: {{ (default .Values.loadbalancerURL .Values.global.loadbalancerURL) | quote }}
  MEMORY: {{ .Values.java.memory | quote }}
  DEPLOY_MODE: KUBERNETES_ONPREM
  API_VERSION: 'release-gateway:182'
  LOG_SVC_GLOBAL_TOKEN: c76e567a-b341-404d-a8dd-d9738714eb82
  TI_SVC_GLOBAL_TOKEN: 78d16b66-4b4c-11eb-8377-acde48001122
  CACHE_TYPE: REDIS
  TOKEN_CACHE_TTL: '300'
  JAVA_ADVANCED_FLAGS: {{ .Values.java.advancedFlags | quote }}
  USE_SENTINEL: {{ .Values.global.database.redis.installed  | quote }}
  SENTINEL_MASTER_NAME: 'harness-redis'
  REDIS_PORT: {{ include "gateway.redisPort" (dict "context" .Values.global.database.redis) | quote }}
  REDIS_SENTINELS: {{ include "gateway.redisHost" (dict "context" .Values.global.database.redis) }}
  REDIS_HOST: {{ include "gateway.redisHost" (dict "context" .Values.global.database.redis) }}
  HARNESS_ENABLE_NG_AUTH_UI : 'true'
  {{- if .Values.global.mongoSSL }}
  MONGO_SSL_CONFIG: "true"
  MONGO_SSL_CA_TRUST_STORE_PATH: /opt/harness/keystore.jks
  MONGO_SSL_CA_TRUST_STORE_PASSWORD: password
  {{- end }}
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
