{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: migrator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "migrator.labels" . | nindent 4 }}
  annotations: {}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: migrator
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
  targetCPUUtilizationPercentage : {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{ end }}
{{- end }}
