apiVersion: v1
kind: Secret
metadata:
  name: {{ include "migrator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "migrator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "migrator.generateSecrets" . }}