apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: manager-iterator
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: manager-iterator
