apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}
data:
  DEPLOY_MODE: {{.Values.DEPLOY_MODE}}
  MEMORY: {{.Values.memory | quote}}
  GOOGLE_APPLICATION_CREDENTIALS: /opt/harness/svc/cloud_stackdriver.json
  STACK_DRIVER_LOGGING_ENABLED: {{.Values.STACK_DRIVER_LOGGING_ENABLED | quote}}
  EVENTS_FRAMEWORK_REDIS_URL: {{.Values.EVENTS_FRAMEWORK_REDIS_URL}}
  EVENTS_FRAMEWORK_USE_SENTINEL: {{.Values.EVENTS_FRAMEWORK_USE_SENTINEL | quote}}
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME: {{.Values.EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME}}
  EVENTS_FRAMEWORK_REDIS_SENTINELS: {{.Values.EVENTS_FRAMEWORK_REDIS_SENTINELS}}
  EVENTS_FRAMEWORK_ENV_NAMESPACE: {{.Values.EVENTS_FRAMEWORK_ENV_NAMESPACE}}
  EVENTS_FRAMEWORK_REDIS_PASSWORD: {{.Values.EVENTS_FRAMEWORK_REDIS_PASSWORD | quote}}
  EVENTS_FRAMEWORK_REDIS_SSL_ENABLED: {{.Values.EVENTS_FRAMEWORK_REDIS_SSL_ENABLED | quote}}
  EVENTS_FRAMEWORK_REDIS_SSL_CA_TRUST_STORE_PATH: {{.Values.EVENTS_FRAMEWORK_REDIS_SSL_CA_TRUST_STORE_PATH}}
  EVENTS_FRAMEWORK_REDIS_SSL_CA_TRUST_STORE_PASSWORD: {{.Values.EVENTS_FRAMEWORK_REDIS_SSL_CA_TRUST_STORE_PASSWORD  | quote}}
  REDIS_LOCK_CONFIG_USE_SENTINEL: {{.Values.REDIS_LOCK_CONFIG_USE_SENTINEL | quote}}
  REDIS_LOCK_CONFIG_SENTINEL_MASTER_NAME: {{.Values.REDIS_LOCK_CONFIG_SENTINEL_MASTER_NAME | quote}}
  REDIS_LOCK_CONFIG_REDIS_URL: {{.Values.REDIS_LOCK_CONFIG_REDIS_URL | quote}}
  REDIS_LOCK_CONFIG_REDIS_SENTINELS: {{.Values.REDIS_LOCK_CONFIG_REDIS_SENTINELS | quote}}
  REDIS_LOCK_CONFIG_ENV_NAMESPACE: {{.Values.REDIS_LOCK_CONFIG_ENV_NAMESPACE | quote}}
  REDIS_LOCK_CONFIG_REDIS_USERNAME: {{.Values.REDIS_LOCK_CONFIG_REDIS_USERNAME | quote}}
  MONGO_DB_SSL_ENABLED_PIPELINE: {{.Values.MONGO_DB_SSL_ENABLED_PIPELINE | quote}}
  COLLECTION_INCLUDE_LIST_PIPELINE: {{.Values.COLLECTION_INCLUDE_LIST_PIPELINE | quote}}
  DEBEZIUM_NAME_PIPELINE: {{.Values.DEBEZIUM_NAME_PIPELINE | quote}}
  MONGODB_NAME_PIPELINE: {{.Values.MONGODB_NAME_PIPELINE | quote}}
  DATABASE_INCLUDE_LIST_PIPELINE: {{.Values.DATABASE_INCLUDE_LIST_PIPELINE | quote}}
  REDIS_STREAM_SIZE_PIPELINE: {{.Values.REDIS_STREAM_SIZE_PIPELINE | quote}}
  SNAPSHOT_MODE_PIPELINE: {{.Values.SNAPSHOT_MODE_PIPELINE | quote}}
  ENABLE_APPDYNAMICS: {{.Values.ENABLE_APPDYNAMICS | quote}}
  APPDYNAMICS_AGENT_APPLICATION_NAME: {{.Values.APPDYNAMICS_AGENT_APPLICATION_NAME | quote}}
  APPDYNAMICS_AGENT_ACCOUNT_NAME: {{.Values.APPDYNAMICS_AGENT_ACCOUNT_NAME | quote}}
  APPDYNAMICS_CONTROLLER_HOST_NAME: {{.Values.APPDYNAMICS_CONTROLLER_HOST_NAME | quote}}
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: {{.Values.APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY | quote}}
  APPDYNAMICS_AGENT_TIER_NAME: {{.Values.APPDYNAMICS_AGENT_TIER_NAME | quote}}
  APPDYNAMICS_CONTROLLER_PORT: "443"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "true"
  ENV: {{.Values.ENV | quote}}
  JAVA_ADVANCED_FLAGS:  {{.Values.flags}}
  MAX_QUEUE_SIZE_PIPELINE: {{.Values.MAX_QUEUE_SIZE_PIPELINE | quote}}
  MAX_BATCH_SIZE_PIPELINE: {{.Values.MAX_BATCH_SIZE_PIPELINE | quote}}
  MAX_QUEUE_SIZE_IN_BYTES_PIPELINE: {{.Values.MAX_QUEUE_SIZE_IN_BYTES_PIPELINE | quote}}
  POLL_INTERVAL_MS_PIPELINE: {{.Values.POLL_INTERVAL_MS_PIPELINE | quote}}
  FIELD_EXCLUDE_LIST_PIPELINE: {{.Values.FIELD_EXCLUDE_LIST_PIPELINE | quote}}
  MONGODB_CONNECTION_STRING_PIPELINE: {{.Values.MONGODB_CONNECTION_STRING_PIPELINE | quote}}
  LIST_OF_ERROR_CODES_FOR_OFFSET_RESET: {{.Values.LIST_OF_ERROR_CODES_FOR_OFFSET_RESET | quote}}

  IS_ENABLED_APPLICATIONS: {{.Values.IS_ENABLED_APPLICATIONS | quote}}
  MONGO_DB_SSL_ENABLED_APPLICATIONS: {{.Values.MONGO_DB_SSL_ENABLED_APPLICATIONS | quote}}
  COLLECTION_INCLUDE_LIST_APPLICATIONS: {{.Values.COLLECTION_INCLUDE_LIST_APPLICATIONS | quote}}
  DEBEZIUM_NAME_APPLICATIONS: {{.Values.DEBEZIUM_NAME_APPLICATIONS | quote}}
  MONGODB_NAME_APPLICATIONS: {{.Values.MONGODB_NAME_APPLICATIONS | quote}}
  DATABASE_INCLUDE_LIST_APPLICATIONS: {{.Values.DATABASE_INCLUDE_LIST_APPLICATIONS | quote}}
  REDIS_STREAM_SIZE_APPLICATIONS: {{.Values.REDIS_STREAM_SIZE_APPLICATIONS | quote}}
  SNAPSHOT_MODE_APPLICATIONS: {{.Values.SNAPSHOT_MODE_APPLICATIONS | quote}}
  MAX_QUEUE_SIZE_APPLICATIONS: {{.Values.MAX_QUEUE_SIZE_APPLICATIONS | quote}}
  MAX_BATCH_SIZE_APPLICATIONS: {{.Values.MAX_BATCH_SIZE_APPLICATIONS | quote}}
  MAX_QUEUE_SIZE_IN_BYTES_APPLICATIONS: {{.Values.MAX_QUEUE_SIZE_IN_BYTES_APPLICATIONS | quote}}
  POLL_INTERVAL_MS_APPLICATIONS: {{.Values.POLL_INTERVAL_MS_APPLICATIONS | quote}}
  FIELD_EXCLUDE_LIST_APPLICATIONS: {{.Values.FIELD_EXCLUDE_LIST_APPLICATIONS | quote}}
  MONGODB_CONNECTION_STRING_APPLICATIONS: {{.Values.MONGODB_CONNECTION_STRING_APPLICATIONS | quote}}

  SNAPSHOT_EVENTS_FRAMEWORK_REDIS_URL: {{.Values.SNAPSHOT_EVENTS_FRAMEWORK_REDIS_URL | quote}}
  SNAPSHOT_EVENTS_FRAMEWORK_ENV_NAMESPACE: {{.Values.SNAPSHOT_EVENTS_FRAMEWORK_ENV_NAMESPACE | quote}}
  IS_ENABLED_PIPELINE_SNAPSHOT: {{.Values.IS_ENABLED_PIPELINE_SNAPSHOT | quote}}
  MONGO_DB_SSL_ENABLED_PIPELINE_SNAPSHOT: {{.Values.MONGO_DB_SSL_ENABLED_PIPELINE_SNAPSHOT | quote}}
  DATABASE_INCLUDE_LIST_PIPELINE_SNAPSHOT: {{.Values.DATABASE_INCLUDE_LIST_PIPELINE_SNAPSHOT | quote}}
  COLLECTION_INCLUDE_LIST_PIPELINE_SNAPSHOT: {{.Values.COLLECTION_INCLUDE_LIST_PIPELINE_SNAPSHOT | quote}}
  REDIS_STREAM_SIZE_PIPELINE_SNAPSHOT: {{.Values.REDIS_STREAM_SIZE_PIPELINE_SNAPSHOT | quote}}
  FIELD_EXCLUDE_LIST_PIPELINE_SNAPSHOT: {{.Values.FIELD_EXCLUDE_LIST_PIPELINE_SNAPSHOT | quote}}
  MONGODB_CONNECTION_STRING_PIPELINE_SNAPSHOT: {{.Values.MONGODB_CONNECTION_STRING_PIPELINE_SNAPSHOT | quote}}

  IS_ENABLED_PLG: {{.Values.IS_ENABLED_PLG | quote}}
  MONGO_DB_SSL_ENABLED_PLG: {{.Values.MONGO_DB_SSL_ENABLED_PLG | quote}}
  COLLECTION_INCLUDE_LIST_PLG: {{.Values.COLLECTION_INCLUDE_LIST_PLG | quote}}
  DEBEZIUM_NAME_PLG: {{.Values.DEBEZIUM_NAME_PLG | quote}}
  MONGODB_NAME_PLG: {{.Values.MONGODB_NAME_PLG | quote}}
  DATABASE_INCLUDE_LIST_PLG: {{.Values.DATABASE_INCLUDE_LIST_PLG | quote}}
  REDIS_STREAM_SIZE_PLG: {{.Values.REDIS_STREAM_SIZE_PLG | quote}}
  SNAPSHOT_MODE_PLG: {{.Values.SNAPSHOT_MODE_PLG | quote}}
  MAX_QUEUE_SIZE_PLG: {{.Values.MAX_QUEUE_SIZE_PLG | quote}}
  MAX_BATCH_SIZE_PLG: {{.Values.MAX_BATCH_SIZE_PLG | quote}}
  MAX_QUEUE_SIZE_IN_BYTES_PLG: {{.Values.MAX_QUEUE_SIZE_IN_BYTES_PLG | quote}}
  POLL_INTERVAL_MS_PLG: {{.Values.POLL_INTERVAL_MS_PLG | quote}}
  MONGODB_CONNECTION_STRING_PLG: {{.Values.MONGODB_CONNECTION_STRING_PLG | quote}}

  ENABLE_PROMETHEUS_COLLECTOR: {{.Values.ENABLE_PROMETHEUS_COLLECTOR | quote}}
  PROMETHEUS_COLLECTOR_PORT: {{.Values.PROMETHEUS_COLLECTOR_PORT | quote}}

  IS_ENABLED_SSCA: {{.Values.IS_ENABLED_SSCA | quote}}
  MONGO_DB_SSL_ENABLED_SSCA: {{.Values.MONGO_DB_SSL_ENABLED_SSCA | quote}}
  COLLECTION_INCLUDE_LIST_SSCA: {{.Values.COLLECTION_INCLUDE_LIST_SSCA | quote}}
  DEBEZIUM_NAME_SSCA: {{.Values.DEBEZIUM_NAME_SSCA | quote}}
  MONGODB_NAME_SSCA: {{.Values.MONGODB_NAME_SSCA | quote}}
  DATABASE_INCLUDE_LIST_SSCA: {{.Values.DATABASE_INCLUDE_LIST_SSCA | quote}}
  REDIS_STREAM_SIZE_SSCA: {{.Values.REDIS_STREAM_SIZE_SSCA | quote}}
  SNAPSHOT_MODE_SSCA: {{.Values.SNAPSHOT_MODE_SSCA | quote}}
  MAX_QUEUE_SIZE_SSCA: {{.Values.MAX_QUEUE_SIZE_SSCA | quote}}
  MAX_BATCH_SIZE_SSCA: {{.Values.MAX_BATCH_SIZE_SSCA | quote}}
  MAX_QUEUE_SIZE_IN_BYTES_SSCA: {{.Values.MAX_QUEUE_SIZE_IN_BYTES_SSCA | quote}}
  POLL_INTERVAL_MS_SSCA: {{.Values.POLL_INTERVAL_MS_SSCA | quote}}
  MONGODB_CONNECTION_STRING_SSCA: {{.Values.MONGODB_CONNECTION_STRING_SSCA | quote}}
  JAVA_17_FLAGS: {{.Values.JAVA_17_FLAGS}}
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: {{.Values.name}}
#stringData:
#  CF_CLIENT_API_KEY: {{.Values.CF_CLIENT_API_KEY}}
#
#type: Opaque
#
#---
#  {{- if .Values.dockercfg}}
#apiVersion: v1
#kind: Secret
#metadata:
#  name: dockerhub-harness-debezium-svc
#  annotations:
#    harness.io/skip-versioning: "true"
#data:
#  .dockercfg: {{.Values.dockercfg}}
#type: kubernetes.io/dockercfg
#  {{- end}}
#
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: service-accounts-{{.Values.name}}
#data:
#  redis-labs-ca-truststore: {{.Values.redislabsCATruststore}}
#  cloud-data-store: {{.Values.ng_service_account}}
