{{- if .Values.autoscaling.enabled }}
apiVersion: {{ include "harnesscommon.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name: ng-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ng-manager.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ng-manager
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{ include "harnesscommon.hpa.metrics.apiVersion" . }}
{{- end }}
