apiVersion: v2
name: platform
description: Helm chart for Harness Platform
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

version: 0.6.24

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.1"
dependencies:
  - name: access-control
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../access-control"
  - name: change-data-capture
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../change-data-capture"
  - name: cv-nextgen
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../cv-nextgen"
  - name: gateway
    version: 0.3.x
    repository: "file://../gateway"
  - name: harness-secrets
    version: 0.3.x
    condition: harness-secrets.enabled
    repository: "file://../secrets"
  - name: harness-manager
    version: 0.3.x
    repository: "file://../harness-manager"
  - name: delegate-proxy
    version: 0.3.x
    repository: "file://../delegate-proxy"
  - name: le-nextgen
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../le-nextgen"
  - name: learning-engine
    condition: global.cg.enabled
    version: 0.4.x
    repository: "file://../learning-engine"
  - name: log-service
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../log-service"
  - name: migrator
    version: 0.3.x
    condition: global.migrator.enabled
    repository: "file://../migrator"
  - name: minio
    condition: global.ng.enabled
    version: 11.9.1
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 13.1.2
    condition: global.database.mongo.installed
    repository: https://charts.bitnami.com/bitnami
  - name: next-gen-ui
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../next-gen-ui"
  - name: ng-auth-ui
    version: 0.3.x
    repository: "file://../ng-auth-ui"
  - name: ng-manager
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../ng-manager"
  - name: pipeline-service
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../pipeline-service"
  - name: platform-service
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../platform-service"
  - name: redis
    version: 0.2.x
    repository: "https://harness.github.io/helm-redis"
  - name: scm-service
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../scm-service"
  - name: template-service
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../template-service"
  - name: ti-service
    condition: global.ng.enabled
    version: 0.3.x
    repository: "file://../ti-service"
  - name: timescaledb
    condition: timescaledb.enabled
    version: 0.2.x
    repository: "https://harness.github.io/helm-timescaledb"
  - name: ui
    condition: global.cg.enabled
    version: 0.4.x
    repository: "file://../ui"
  - name: verification-svc
    condition: global.cg.enabled
    version: 0.4.x
    repository: "file://../verification-svc"
