apiVersion: v1
kind: Secret
metadata:
  name: clickhouse
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations: {}
type: Opaque
data:
{{- include "harnesssecrets.generateClickhouseSecrets" . }}